---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-token
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
spec:
  secretStoreRef:
    name: doppler-auth-api
    kind: SecretStore
  target:
    name: github-webhook-token
  data:
    - secretKey: token
      remoteRef:
        key: FLUX_GITHUB_TOKEN
