---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-url
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
spec:
  secretStoreRef:
    name: doppler-auth-api
    kind: SecretStore
  target:
    name: slack-url
  data:
    - secretKey: address
      remoteRef:
        key: FLUX_SLACK_URL
