---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux
  namespace: flux-system
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - flux.techcasa.io
      secretName: flux-tls
  rules:
    - host: flux.techcasa.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-controller
                port:
                  name: http
