---
# K3s default variables

# K3s version
k3s_version: v1.28.8+k3s1
k3s_install_url: https://get.k3s.io

# Cluster configuration
k3s_cluster_vip: 10.10.101.50
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16

# Directories
k3s_config_dir: /etc/rancher/k3s
k3s_data_dir: /var/lib/rancher/k3s

# Features
k3s_disable_components:
  - traefik  # We'll install our own
  - servicelb  # Using MetalLB instead

k3s_enable_components: []

# TLS SANs
k3s_tls_san:
  - "{{ k3s_cluster_vip }}"
  - k3s.{{ domain_name }}

# MetalLB
metallb_enabled: true
metallb_ip_range: "10.10.101.60-10.10.101.100"

# Longhorn storage
longhorn_enabled: true
longhorn_storage_path: /var/lib/longhorn

# Monitoring
prometheus_enabled: false
grafana_enabled: false

# Networking
flannel_backend: vxlan
