---
# Handlers for proxmox_base role

- name: update grub
  command: update-grub

- name: restart pveproxy
  systemd:
    name: pveproxy
    state: restarted

- name: restart pvedaemon
  systemd:
    name: pvedaemon
    state: restarted

- name: restart pve-cluster
  systemd:
    name: pve-cluster
    state: restarted
